project_name: recipes
before:
  hooks:
    - go mod tidy

builds:
  - id: recipes
    main: ./cmd/recipes
    binary: recipes
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

universal_binaries:
  - replace: true

archives:
  - format: tar.gz
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip

brews:
  - name: recipes
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/jphastings/recipes"

    description: "Cookbook recipe format toolbox."
    license: "MIT"

    custom_block: |
      resource("test.melarecipes") do
        url "https://raw.githubusercontent.com/jphastings/recipes/main/mela/fixtures/a+b.melarecipes"
        sha256 "4f72c6ffb2f126adf5df5d79311dfec2335b463da16fe26deff19bdd5579e1b2"
      end

    test: |
      resource("test.melarecipes").stage do
        shell_output("#{bin}/recipes convert --to \"#{testpath}/.melarecipe\"")
        assert_predicate testpath/"example.com/a-title.melarecipe", :exist?
        assert_predicate testpath/"example.com/b-title.melarecipe", :exist?
      end

    repository:
      owner: jphastings
      name: homebrew-tools
      branch: main
      token: "{{ .Env.HOMEBREW_PAT }}"

      pull_request:
        enabled: false

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
