// Code generated by github.com/tvastar/test@v0.0.0-20190923010924-84aa581ec885/cmd/testmd/testmd.go. DO NOT EDIT.

package mela_test

import (
	"fmt"
	"log"

	"github.com/jphastings/recipes/mela"
)

// import github.com/jphastings/recipes/mela
func ExampleOpen() {
	recipes, err := mela.Open("fixtures/a+b.melarecipes")
	if err != nil {
		log.Fatalf("A filesystem error: %v\n", err)
	}

	for i, r := range recipes {
		fmt.Printf("Recipe #%d title: %s\n", i, r.Title)
	}

	// Output:
	// Recipe #0 title: B title
	// Recipe #1 title: A title

}

func ExampleSetBook() {
	recipes, err := mela.Open("fixtures/a.melarecipe")
	if err != nil {
		log.Fatalf("A filesystem error: %v\n", err)
	}

	r := recipes[0]

	// Note: Setting the book details creates a new object with a URN based on a standardised form ISBN-13.
	setErr := r.SetBook("123456789X", mela.MustParsePages("42"), 2)
	if setErr != nil {
		log.Fatalf("Invalid Book details given: %v\n", err)
	}

	fmt.Println("ID:", r.ID)
	fmt.Println("ISBN:", r.Book().ISBN13)
	fmt.Println("Page numbers:", r.Book().Pages)
	fmt.Println("Recipe number:", r.Book().RecipeNumber)

	// Output:
	// ID: urn:isbn:9781234567897#pages=42&recipe=2
	// ISBN: 9781234567897
	// Page numbers: 42
	// Recipe number: 2

}
