// Code generated by pigeon; DO NOT EDIT.

package ingredients

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"math/big"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Ingredient",
			pos:  position{line: 9, col: 1, offset: 58},
			expr: &seqExpr{
				pos: position{line: 10, col: 3, offset: 74},
				exprs: []any{
					&zeroOrOneExpr{
						pos: position{line: 10, col: 3, offset: 74},
						expr: &actionExpr{
							pos: position{line: 10, col: 4, offset: 75},
							run: (*parser).callonIngredient3,
							expr: &seqExpr{
								pos: position{line: 10, col: 4, offset: 75},
								exprs: []any{
									&labeledExpr{
										pos:   position{line: 10, col: 4, offset: 75},
										label: "a",
										expr: &ruleRefExpr{
											pos:  position{line: 10, col: 6, offset: 77},
											name: "Amount",
										},
									},
									&zeroOrOneExpr{
										pos: position{line: 10, col: 13, offset: 84},
										expr: &ruleRefExpr{
											pos:  position{line: 10, col: 13, offset: 84},
											name: "_Space",
										},
									},
								},
							},
						},
					},
					&zeroOrOneExpr{
						pos: position{line: 13, col: 3, offset: 120},
						expr: &actionExpr{
							pos: position{line: 13, col: 4, offset: 121},
							run: (*parser).callonIngredient10,
							expr: &seqExpr{
								pos: position{line: 13, col: 4, offset: 121},
								exprs: []any{
									&labeledExpr{
										pos:   position{line: 13, col: 4, offset: 121},
										label: "u",
										expr: &ruleRefExpr{
											pos:  position{line: 13, col: 6, offset: 123},
											name: "Unit",
										},
									},
									&zeroOrOneExpr{
										pos: position{line: 13, col: 11, offset: 128},
										expr: &litMatcher{
											pos:        position{line: 13, col: 11, offset: 128},
											val:        " of",
											ignoreCase: false,
											want:       "\" of\"",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 13, col: 18, offset: 135},
										name: "_Space",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 16, col: 4, offset: 171},
						run: (*parser).callonIngredient17,
						expr: &labeledExpr{
							pos:   position{line: 16, col: 4, offset: 171},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 16, col: 9, offset: 176},
								name: "String",
							},
						},
					},
					&notExpr{
						pos: position{line: 19, col: 3, offset: 213},
						expr: &anyMatcher{
							line: 19, col: 4, offset: 214,
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 21, col: 1, offset: 217},
			expr: &actionExpr{
				pos: position{line: 21, col: 11, offset: 227},
				run: (*parser).callonString1,
				expr: &oneOrMoreExpr{
					pos: position{line: 21, col: 11, offset: 227},
					expr: &anyMatcher{
						line: 21, col: 11, offset: 227,
					},
				},
			},
		},
		{
			name: "Amount",
			pos:  position{line: 25, col: 1, offset: 264},
			expr: &choiceExpr{
				pos: position{line: 26, col: 3, offset: 278},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 26, col: 3, offset: 278},
						name: "WordNumbers",
					},
					&actionExpr{
						pos: position{line: 27, col: 4, offset: 295},
						run: (*parser).callonAmount3,
						expr: &seqExpr{
							pos: position{line: 27, col: 4, offset: 295},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 27, col: 4, offset: 295},
									label: "i",
									expr: &ruleRefExpr{
										pos:  position{line: 27, col: 6, offset: 297},
										name: "Integer",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 27, col: 14, offset: 305},
									name: "_Space",
								},
								&labeledExpr{
									pos:   position{line: 27, col: 21, offset: 312},
									label: "af",
									expr: &ruleRefExpr{
										pos:  position{line: 27, col: 24, offset: 315},
										name: "AsciiFraction",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 30, col: 3, offset: 402},
						name: "AsciiFraction",
					},
					&actionExpr{
						pos: position{line: 31, col: 4, offset: 421},
						run: (*parser).callonAmount11,
						expr: &seqExpr{
							pos: position{line: 31, col: 4, offset: 421},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 31, col: 4, offset: 421},
									label: "ff",
									expr: &ruleRefExpr{
										pos:  position{line: 31, col: 7, offset: 424},
										name: "Fraction",
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 31, col: 16, offset: 433},
									expr: &litMatcher{
										pos:        position{line: 31, col: 16, offset: 433},
										val:        " a",
										ignoreCase: false,
										want:       "\" a\"",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 32, col: 3, offset: 463},
						name: "Decimal",
					},
					&actionExpr{
						pos: position{line: 33, col: 4, offset: 476},
						run: (*parser).callonAmount18,
						expr: &seqExpr{
							pos: position{line: 33, col: 4, offset: 476},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 33, col: 4, offset: 476},
									label: "i",
									expr: &ruleRefExpr{
										pos:  position{line: 33, col: 6, offset: 478},
										name: "Integer",
									},
								},
								&labeledExpr{
									pos:   position{line: 33, col: 14, offset: 486},
									label: "f",
									expr: &zeroOrOneExpr{
										pos: position{line: 33, col: 16, offset: 488},
										expr: &ruleRefExpr{
											pos:  position{line: 33, col: 16, offset: 488},
											name: "Fraction",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AsciiFraction",
			pos:  position{line: 41, col: 1, offset: 613},
			expr: &actionExpr{
				pos: position{line: 41, col: 18, offset: 630},
				run: (*parser).callonAsciiFraction1,
				expr: &seqExpr{
					pos: position{line: 41, col: 18, offset: 630},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 41, col: 18, offset: 630},
							label: "num",
							expr: &ruleRefExpr{
								pos:  position{line: 41, col: 22, offset: 634},
								name: "Integer",
							},
						},
						&litMatcher{
							pos:        position{line: 41, col: 30, offset: 642},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
						&labeledExpr{
							pos:   position{line: 41, col: 34, offset: 646},
							label: "den",
							expr: &ruleRefExpr{
								pos:  position{line: 41, col: 38, offset: 650},
								name: "Integer",
							},
						},
					},
				},
			},
		},
		{
			name: "WordNumbers",
			pos:  position{line: 49, col: 1, offset: 821},
			expr: &choiceExpr{
				pos: position{line: 50, col: 3, offset: 840},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 50, col: 3, offset: 840},
						run: (*parser).callonWordNumbers2,
						expr: &litMatcher{
							pos:        position{line: 50, col: 3, offset: 840},
							val:        "a",
							ignoreCase: false,
							want:       "\"a\"",
						},
					},
					&actionExpr{
						pos: position{line: 53, col: 3, offset: 888},
						run: (*parser).callonWordNumbers4,
						expr: &seqExpr{
							pos: position{line: 53, col: 3, offset: 888},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 53, col: 3, offset: 888},
									val:        "half",
									ignoreCase: false,
									want:       "\"half\"",
								},
								&zeroOrOneExpr{
									pos: position{line: 53, col: 10, offset: 895},
									expr: &litMatcher{
										pos:        position{line: 53, col: 10, offset: 895},
										val:        " a",
										ignoreCase: false,
										want:       "\" a\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 58, col: 1, offset: 943},
			expr: &actionExpr{
				pos: position{line: 58, col: 12, offset: 954},
				run: (*parser).callonInteger1,
				expr: &oneOrMoreExpr{
					pos: position{line: 58, col: 12, offset: 954},
					expr: &charClassMatcher{
						pos:        position{line: 58, col: 12, offset: 954},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Fraction",
			pos:  position{line: 66, col: 1, offset: 1087},
			expr: &choiceExpr{
				pos: position{line: 67, col: 3, offset: 1103},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 67, col: 3, offset: 1103},
						run: (*parser).callonFraction2,
						expr: &litMatcher{
							pos:        position{line: 67, col: 3, offset: 1103},
							val:        "½",
							ignoreCase: false,
							want:       "\"½\"",
						},
					},
					&actionExpr{
						pos: position{line: 70, col: 3, offset: 1151},
						run: (*parser).callonFraction4,
						expr: &litMatcher{
							pos:        position{line: 70, col: 3, offset: 1151},
							val:        "⅓",
							ignoreCase: false,
							want:       "\"⅓\"",
						},
					},
					&actionExpr{
						pos: position{line: 73, col: 3, offset: 1200},
						run: (*parser).callonFraction6,
						expr: &litMatcher{
							pos:        position{line: 73, col: 3, offset: 1200},
							val:        "¼",
							ignoreCase: false,
							want:       "\"¼\"",
						},
					},
					&actionExpr{
						pos: position{line: 76, col: 3, offset: 1248},
						run: (*parser).callonFraction8,
						expr: &litMatcher{
							pos:        position{line: 76, col: 3, offset: 1248},
							val:        "⅛",
							ignoreCase: false,
							want:       "\"⅛\"",
						},
					},
					&actionExpr{
						pos: position{line: 79, col: 3, offset: 1297},
						run: (*parser).callonFraction10,
						expr: &litMatcher{
							pos:        position{line: 79, col: 3, offset: 1297},
							val:        "⅔",
							ignoreCase: false,
							want:       "\"⅔\"",
						},
					},
					&actionExpr{
						pos: position{line: 82, col: 3, offset: 1346},
						run: (*parser).callonFraction12,
						expr: &litMatcher{
							pos:        position{line: 82, col: 3, offset: 1346},
							val:        "¾",
							ignoreCase: false,
							want:       "\"¾\"",
						},
					},
					&actionExpr{
						pos: position{line: 85, col: 3, offset: 1394},
						run: (*parser).callonFraction14,
						expr: &litMatcher{
							pos:        position{line: 85, col: 3, offset: 1394},
							val:        "⅜",
							ignoreCase: false,
							want:       "\"⅜\"",
						},
					},
					&actionExpr{
						pos: position{line: 88, col: 3, offset: 1443},
						run: (*parser).callonFraction16,
						expr: &litMatcher{
							pos:        position{line: 88, col: 3, offset: 1443},
							val:        "⅝",
							ignoreCase: false,
							want:       "\"⅝\"",
						},
					},
					&actionExpr{
						pos: position{line: 91, col: 3, offset: 1492},
						run: (*parser).callonFraction18,
						expr: &litMatcher{
							pos:        position{line: 91, col: 3, offset: 1492},
							val:        "⅞",
							ignoreCase: false,
							want:       "\"⅞\"",
						},
					},
				},
			},
		},
		{
			name: "Decimal",
			pos:  position{line: 96, col: 1, offset: 1540},
			expr: &actionExpr{
				pos: position{line: 96, col: 12, offset: 1551},
				run: (*parser).callonDecimal1,
				expr: &seqExpr{
					pos: position{line: 96, col: 12, offset: 1551},
					exprs: []any{
						&oneOrMoreExpr{
							pos: position{line: 96, col: 12, offset: 1551},
							expr: &charClassMatcher{
								pos:        position{line: 96, col: 12, offset: 1551},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&litMatcher{
							pos:        position{line: 96, col: 19, offset: 1558},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&oneOrMoreExpr{
							pos: position{line: 96, col: 23, offset: 1562},
							expr: &charClassMatcher{
								pos:        position{line: 96, col: 23, offset: 1562},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Unit",
			pos:  position{line: 104, col: 1, offset: 1726},
			expr: &choiceExpr{
				pos: position{line: 105, col: 3, offset: 1738},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 105, col: 4, offset: 1739},
						run: (*parser).callonUnit2,
						expr: &seqExpr{
							pos: position{line: 105, col: 4, offset: 1739},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 105, col: 4, offset: 1739},
									val:        "a",
									ignoreCase: false,
									want:       "\"a\"",
								},
								&andExpr{
									pos: position{line: 105, col: 8, offset: 1743},
									expr: &litMatcher{
										pos:        position{line: 105, col: 9, offset: 1744},
										val:        " ",
										ignoreCase: false,
										want:       "\" \"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 108, col: 4, offset: 1785},
						run: (*parser).callonUnit7,
						expr: &seqExpr{
							pos: position{line: 108, col: 4, offset: 1785},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 108, col: 4, offset: 1785},
									val:        "bunch",
									ignoreCase: false,
									want:       "\"bunch\"",
								},
								&zeroOrOneExpr{
									pos: position{line: 108, col: 12, offset: 1793},
									expr: &litMatcher{
										pos:        position{line: 108, col: 12, offset: 1793},
										val:        "es",
										ignoreCase: false,
										want:       "\"es\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 111, col: 4, offset: 1837},
						run: (*parser).callonUnit12,
						expr: &seqExpr{
							pos: position{line: 111, col: 4, offset: 1837},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 111, col: 4, offset: 1837},
									val:        "pinch",
									ignoreCase: false,
									want:       "\"pinch\"",
								},
								&zeroOrOneExpr{
									pos: position{line: 111, col: 12, offset: 1845},
									expr: &litMatcher{
										pos:        position{line: 111, col: 12, offset: 1845},
										val:        "es",
										ignoreCase: false,
										want:       "\"es\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 114, col: 4, offset: 1889},
						run: (*parser).callonUnit17,
						expr: &seqExpr{
							pos: position{line: 114, col: 4, offset: 1889},
							exprs: []any{
								&choiceExpr{
									pos: position{line: 114, col: 5, offset: 1890},
									alternatives: []any{
										&litMatcher{
											pos:        position{line: 114, col: 5, offset: 1890},
											val:        "tablespoon",
											ignoreCase: false,
											want:       "\"tablespoon\"",
										},
										&litMatcher{
											pos:        position{line: 114, col: 20, offset: 1905},
											val:        "tbsp",
											ignoreCase: false,
											want:       "\"tbsp\"",
										},
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 114, col: 28, offset: 1913},
									expr: &litMatcher{
										pos:        position{line: 114, col: 28, offset: 1913},
										val:        "s",
										ignoreCase: false,
										want:       "\"s\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 117, col: 4, offset: 1961},
						run: (*parser).callonUnit24,
						expr: &seqExpr{
							pos: position{line: 117, col: 4, offset: 1961},
							exprs: []any{
								&choiceExpr{
									pos: position{line: 117, col: 5, offset: 1962},
									alternatives: []any{
										&litMatcher{
											pos:        position{line: 117, col: 5, offset: 1962},
											val:        "teaspoon",
											ignoreCase: false,
											want:       "\"teaspoon\"",
										},
										&litMatcher{
											pos:        position{line: 117, col: 18, offset: 1975},
											val:        "tsp",
											ignoreCase: false,
											want:       "\"tsp\"",
										},
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 117, col: 25, offset: 1982},
									expr: &litMatcher{
										pos:        position{line: 117, col: 25, offset: 1982},
										val:        "s",
										ignoreCase: false,
										want:       "\"s\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 120, col: 4, offset: 2028},
						run: (*parser).callonUnit31,
						expr: &seqExpr{
							pos: position{line: 120, col: 4, offset: 2028},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 120, col: 4, offset: 2028},
									val:        "cup",
									ignoreCase: false,
									want:       "\"cup\"",
								},
								&zeroOrOneExpr{
									pos: position{line: 120, col: 10, offset: 2034},
									expr: &litMatcher{
										pos:        position{line: 120, col: 10, offset: 2034},
										val:        "s",
										ignoreCase: false,
										want:       "\"s\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 123, col: 4, offset: 2075},
						run: (*parser).callonUnit36,
						expr: &seqExpr{
							pos: position{line: 123, col: 4, offset: 2075},
							exprs: []any{
								&choiceExpr{
									pos: position{line: 123, col: 5, offset: 2076},
									alternatives: []any{
										&litMatcher{
											pos:        position{line: 123, col: 5, offset: 2076},
											val:        "gram",
											ignoreCase: false,
											want:       "\"gram\"",
										},
										&litMatcher{
											pos:        position{line: 123, col: 14, offset: 2085},
											val:        "g",
											ignoreCase: false,
											want:       "\"g\"",
										},
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 123, col: 19, offset: 2090},
									expr: &litMatcher{
										pos:        position{line: 123, col: 19, offset: 2090},
										val:        "s",
										ignoreCase: false,
										want:       "\"s\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 126, col: 4, offset: 2132},
						run: (*parser).callonUnit43,
						expr: &seqExpr{
							pos: position{line: 126, col: 4, offset: 2132},
							exprs: []any{
								&choiceExpr{
									pos: position{line: 126, col: 5, offset: 2133},
									alternatives: []any{
										&litMatcher{
											pos:        position{line: 126, col: 5, offset: 2133},
											val:        "kilogram",
											ignoreCase: false,
											want:       "\"kilogram\"",
										},
										&litMatcher{
											pos:        position{line: 126, col: 18, offset: 2146},
											val:        "kg",
											ignoreCase: false,
											want:       "\"kg\"",
										},
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 126, col: 24, offset: 2152},
									expr: &litMatcher{
										pos:        position{line: 126, col: 24, offset: 2152},
										val:        "s",
										ignoreCase: false,
										want:       "\"s\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 129, col: 4, offset: 2198},
						run: (*parser).callonUnit50,
						expr: &seqExpr{
							pos: position{line: 129, col: 4, offset: 2198},
							exprs: []any{
								&choiceExpr{
									pos: position{line: 129, col: 5, offset: 2199},
									alternatives: []any{
										&litMatcher{
											pos:        position{line: 129, col: 5, offset: 2199},
											val:        "pound",
											ignoreCase: false,
											want:       "\"pound\"",
										},
										&litMatcher{
											pos:        position{line: 129, col: 15, offset: 2209},
											val:        "lb",
											ignoreCase: false,
											want:       "\"lb\"",
										},
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 129, col: 21, offset: 2215},
									expr: &litMatcher{
										pos:        position{line: 129, col: 21, offset: 2215},
										val:        "s",
										ignoreCase: false,
										want:       "\"s\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 132, col: 4, offset: 2258},
						run: (*parser).callonUnit57,
						expr: &seqExpr{
							pos: position{line: 132, col: 4, offset: 2258},
							exprs: []any{
								&choiceExpr{
									pos: position{line: 132, col: 5, offset: 2259},
									alternatives: []any{
										&litMatcher{
											pos:        position{line: 132, col: 5, offset: 2259},
											val:        "ounce",
											ignoreCase: false,
											want:       "\"ounce\"",
										},
										&litMatcher{
											pos:        position{line: 132, col: 15, offset: 2269},
											val:        "oz",
											ignoreCase: false,
											want:       "\"oz\"",
										},
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 132, col: 21, offset: 2275},
									expr: &litMatcher{
										pos:        position{line: 132, col: 21, offset: 2275},
										val:        "s",
										ignoreCase: false,
										want:       "\"s\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 135, col: 4, offset: 2318},
						run: (*parser).callonUnit64,
						expr: &seqExpr{
							pos: position{line: 135, col: 4, offset: 2318},
							exprs: []any{
								&choiceExpr{
									pos: position{line: 135, col: 5, offset: 2319},
									alternatives: []any{
										&litMatcher{
											pos:        position{line: 135, col: 5, offset: 2319},
											val:        "millilitre",
											ignoreCase: false,
											want:       "\"millilitre\"",
										},
										&litMatcher{
											pos:        position{line: 135, col: 20, offset: 2334},
											val:        "ml",
											ignoreCase: false,
											want:       "\"ml\"",
										},
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 135, col: 26, offset: 2340},
									expr: &litMatcher{
										pos:        position{line: 135, col: 26, offset: 2340},
										val:        "s",
										ignoreCase: false,
										want:       "\"s\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 138, col: 4, offset: 2388},
						run: (*parser).callonUnit71,
						expr: &seqExpr{
							pos: position{line: 138, col: 4, offset: 2388},
							exprs: []any{
								&choiceExpr{
									pos: position{line: 138, col: 5, offset: 2389},
									alternatives: []any{
										&litMatcher{
											pos:        position{line: 138, col: 5, offset: 2389},
											val:        "centilitre",
											ignoreCase: false,
											want:       "\"centilitre\"",
										},
										&litMatcher{
											pos:        position{line: 138, col: 20, offset: 2404},
											val:        "cl",
											ignoreCase: false,
											want:       "\"cl\"",
										},
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 138, col: 26, offset: 2410},
									expr: &litMatcher{
										pos:        position{line: 138, col: 26, offset: 2410},
										val:        "s",
										ignoreCase: false,
										want:       "\"s\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 141, col: 4, offset: 2458},
						run: (*parser).callonUnit78,
						expr: &seqExpr{
							pos: position{line: 141, col: 4, offset: 2458},
							exprs: []any{
								&choiceExpr{
									pos: position{line: 141, col: 5, offset: 2459},
									alternatives: []any{
										&litMatcher{
											pos:        position{line: 141, col: 5, offset: 2459},
											val:        "decilitre",
											ignoreCase: false,
											want:       "\"decilitre\"",
										},
										&litMatcher{
											pos:        position{line: 141, col: 19, offset: 2473},
											val:        "dl",
											ignoreCase: false,
											want:       "\"dl\"",
										},
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 141, col: 25, offset: 2479},
									expr: &litMatcher{
										pos:        position{line: 141, col: 25, offset: 2479},
										val:        "s",
										ignoreCase: false,
										want:       "\"s\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 144, col: 4, offset: 2526},
						run: (*parser).callonUnit85,
						expr: &seqExpr{
							pos: position{line: 144, col: 4, offset: 2526},
							exprs: []any{
								&choiceExpr{
									pos: position{line: 144, col: 5, offset: 2527},
									alternatives: []any{
										&litMatcher{
											pos:        position{line: 144, col: 5, offset: 2527},
											val:        "litre",
											ignoreCase: false,
											want:       "\"litre\"",
										},
										&litMatcher{
											pos:        position{line: 144, col: 15, offset: 2537},
											val:        "l",
											ignoreCase: false,
											want:       "\"l\"",
										},
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 144, col: 20, offset: 2542},
									expr: &litMatcher{
										pos:        position{line: 144, col: 20, offset: 2542},
										val:        "s",
										ignoreCase: false,
										want:       "\"s\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 147, col: 4, offset: 2585},
						run: (*parser).callonUnit92,
						expr: &seqExpr{
							pos: position{line: 147, col: 4, offset: 2585},
							exprs: []any{
								&seqExpr{
									pos: position{line: 147, col: 5, offset: 2586},
									exprs: []any{
										&litMatcher{
											pos:        position{line: 147, col: 5, offset: 2586},
											val:        "fl",
											ignoreCase: false,
											want:       "\"fl\"",
										},
										&zeroOrOneExpr{
											pos: position{line: 147, col: 10, offset: 2591},
											expr: &choiceExpr{
												pos: position{line: 147, col: 11, offset: 2592},
												alternatives: []any{
													&litMatcher{
														pos:        position{line: 147, col: 11, offset: 2592},
														val:        "uid",
														ignoreCase: false,
														want:       "\"uid\"",
													},
													&litMatcher{
														pos:        position{line: 147, col: 19, offset: 2600},
														val:        ".",
														ignoreCase: false,
														want:       "\".\"",
													},
												},
											},
										},
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 147, col: 26, offset: 2607},
									expr: &litMatcher{
										pos:        position{line: 147, col: 26, offset: 2607},
										val:        " ",
										ignoreCase: false,
										want:       "\" \"",
									},
								},
								&seqExpr{
									pos: position{line: 147, col: 32, offset: 2613},
									exprs: []any{
										&litMatcher{
											pos:        position{line: 147, col: 32, offset: 2613},
											val:        "o",
											ignoreCase: false,
											want:       "\"o\"",
										},
										&choiceExpr{
											pos: position{line: 147, col: 37, offset: 2618},
											alternatives: []any{
												&seqExpr{
													pos: position{line: 147, col: 37, offset: 2618},
													exprs: []any{
														&litMatcher{
															pos:        position{line: 147, col: 37, offset: 2618},
															val:        "unce",
															ignoreCase: false,
															want:       "\"unce\"",
														},
														&zeroOrOneExpr{
															pos: position{line: 147, col: 44, offset: 2625},
															expr: &litMatcher{
																pos:        position{line: 147, col: 44, offset: 2625},
																val:        "s",
																ignoreCase: false,
																want:       "\"s\"",
															},
														},
													},
												},
												&seqExpr{
													pos: position{line: 147, col: 51, offset: 2632},
													exprs: []any{
														&litMatcher{
															pos:        position{line: 147, col: 51, offset: 2632},
															val:        "z",
															ignoreCase: false,
															want:       "\"z\"",
														},
														&zeroOrOneExpr{
															pos: position{line: 147, col: 55, offset: 2636},
															expr: &litMatcher{
																pos:        position{line: 147, col: 55, offset: 2636},
																val:        ".",
																ignoreCase: false,
																want:       "\".\"",
															},
														},
													},
												},
											},
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 150, col: 4, offset: 2686},
						run: (*parser).callonUnit113,
						expr: &seqExpr{
							pos: position{line: 150, col: 4, offset: 2686},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 150, col: 4, offset: 2686},
									val:        "bottle",
									ignoreCase: false,
									want:       "\"bottle\"",
								},
								&zeroOrOneExpr{
									pos: position{line: 150, col: 13, offset: 2695},
									expr: &litMatcher{
										pos:        position{line: 150, col: 13, offset: 2695},
										val:        "s",
										ignoreCase: false,
										want:       "\"s\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 153, col: 4, offset: 2739},
						run: (*parser).callonUnit118,
						expr: &seqExpr{
							pos: position{line: 153, col: 4, offset: 2739},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 153, col: 4, offset: 2739},
									val:        "can",
									ignoreCase: false,
									want:       "\"can\"",
								},
								&zeroOrOneExpr{
									pos: position{line: 153, col: 10, offset: 2745},
									expr: &litMatcher{
										pos:        position{line: 153, col: 10, offset: 2745},
										val:        "s",
										ignoreCase: false,
										want:       "\"s\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 156, col: 4, offset: 2786},
						run: (*parser).callonUnit123,
						expr: &seqExpr{
							pos: position{line: 156, col: 4, offset: 2786},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 156, col: 4, offset: 2786},
									val:        "packet",
									ignoreCase: false,
									want:       "\"packet\"",
								},
								&zeroOrOneExpr{
									pos: position{line: 156, col: 13, offset: 2795},
									expr: &litMatcher{
										pos:        position{line: 156, col: 13, offset: 2795},
										val:        "s",
										ignoreCase: false,
										want:       "\"s\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "_Space",
			pos:  position{line: 161, col: 1, offset: 2837},
			expr: &litMatcher{
				pos:        position{line: 161, col: 11, offset: 2847},
				val:        " ",
				ignoreCase: false,
				want:       "\" \"",
			},
		},
	},
}

func (c *current) onIngredient3(a any) (any, error) {
	return a, nil

}

func (p *parser) callonIngredient3() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIngredient3(stack["a"])
}

func (c *current) onIngredient10(u any) (any, error) {
	return u, nil

}

func (p *parser) callonIngredient10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIngredient10(stack["u"])
}

func (c *current) onIngredient17(name any) (any, error) {
	return name, nil

}

func (p *parser) callonIngredient17() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIngredient17(stack["name"])
}

func (c *current) onString1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonString1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1()
}

func (c *current) onAmount3(i, af any) (any, error) {
	return new(big.Rat).Add(i.(*big.Rat), af.(*big.Rat)), nil

}

func (p *parser) callonAmount3() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAmount3(stack["i"], stack["af"])
}

func (c *current) onAmount11(ff any) (any, error) {
	return ff, nil
}

func (p *parser) callonAmount11() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAmount11(stack["ff"])
}

func (c *current) onAmount18(i, f any) (any, error) {
	if f != nil {
		return new(big.Rat).Add(i.(*big.Rat), f.(*big.Rat)), nil
	}
	return i, nil

}

func (p *parser) callonAmount18() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAmount18(stack["i"], stack["f"])
}

func (c *current) onAsciiFraction1(num, den any) (any, error) {
	d := den.(*big.Rat)
	if d.Sign() == 0 {
		return nil, errors.New("fraction with zero denominator")
	}
	return new(big.Rat).Quo(num.(*big.Rat), d), nil
}

func (p *parser) callonAsciiFraction1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAsciiFraction1(stack["num"], stack["den"])
}

func (c *current) onWordNumbers2() (any, error) {
	return big.NewRat(1, 1), nil

}

func (p *parser) callonWordNumbers2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWordNumbers2()
}

func (c *current) onWordNumbers4() (any, error) {
	return big.NewRat(1, 2), nil

}

func (p *parser) callonWordNumbers4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWordNumbers4()
}

func (c *current) onInteger1() (any, error) {
	i, err := strconv.Atoi(string(c.text))
	if err != nil {
		return nil, err
	}
	return big.NewRat(int64(i), 1), nil
}

func (p *parser) callonInteger1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

func (c *current) onFraction2() (any, error) {
	return big.NewRat(1, 2), nil

}

func (p *parser) callonFraction2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFraction2()
}

func (c *current) onFraction4() (any, error) {
	return big.NewRat(1, 3), nil

}

func (p *parser) callonFraction4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFraction4()
}

func (c *current) onFraction6() (any, error) {
	return big.NewRat(1, 4), nil

}

func (p *parser) callonFraction6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFraction6()
}

func (c *current) onFraction8() (any, error) {
	return big.NewRat(1, 8), nil

}

func (p *parser) callonFraction8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFraction8()
}

func (c *current) onFraction10() (any, error) {
	return big.NewRat(2, 3), nil

}

func (p *parser) callonFraction10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFraction10()
}

func (c *current) onFraction12() (any, error) {
	return big.NewRat(3, 4), nil

}

func (p *parser) callonFraction12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFraction12()
}

func (c *current) onFraction14() (any, error) {
	return big.NewRat(3, 8), nil

}

func (p *parser) callonFraction14() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFraction14()
}

func (c *current) onFraction16() (any, error) {
	return big.NewRat(5, 8), nil

}

func (p *parser) callonFraction16() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFraction16()
}

func (c *current) onFraction18() (any, error) {
	return big.NewRat(7, 8), nil

}

func (p *parser) callonFraction18() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFraction18()
}

func (c *current) onDecimal1() (any, error) {
	r, ok := (&big.Rat{}).SetString(string(c.text))
	if !ok {
		return nil, fmt.Errorf("unprocessable decimal string: %s", c.text)
	}
	return r, nil
}

func (p *parser) callonDecimal1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDecimal1()
}

func (c *current) onUnit2() (any, error) {
	return UnitItem, nil

}

func (p *parser) callonUnit2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit2()
}

func (c *current) onUnit7() (any, error) {
	return UnitBunch, nil

}

func (p *parser) callonUnit7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit7()
}

func (c *current) onUnit12() (any, error) {
	return UnitPinch, nil

}

func (p *parser) callonUnit12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit12()
}

func (c *current) onUnit17() (any, error) {
	return UnitTablespoon, nil

}

func (p *parser) callonUnit17() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit17()
}

func (c *current) onUnit24() (any, error) {
	return UnitTeaspoon, nil

}

func (p *parser) callonUnit24() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit24()
}

func (c *current) onUnit31() (any, error) {
	return UnitCup, nil

}

func (p *parser) callonUnit31() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit31()
}

func (c *current) onUnit36() (any, error) {
	return UnitGram, nil

}

func (p *parser) callonUnit36() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit36()
}

func (c *current) onUnit43() (any, error) {
	return UnitKilogram, nil

}

func (p *parser) callonUnit43() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit43()
}

func (c *current) onUnit50() (any, error) {
	return UnitPound, nil

}

func (p *parser) callonUnit50() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit50()
}

func (c *current) onUnit57() (any, error) {
	return UnitOunce, nil

}

func (p *parser) callonUnit57() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit57()
}

func (c *current) onUnit64() (any, error) {
	return UnitMillilitre, nil

}

func (p *parser) callonUnit64() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit64()
}

func (c *current) onUnit71() (any, error) {
	return UnitCentilitre, nil

}

func (p *parser) callonUnit71() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit71()
}

func (c *current) onUnit78() (any, error) {
	return UnitDecilitre, nil

}

func (p *parser) callonUnit78() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit78()
}

func (c *current) onUnit85() (any, error) {
	return UnitLitre, nil

}

func (p *parser) callonUnit85() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit85()
}

func (c *current) onUnit92() (any, error) {
	return UnitFluidOunce, nil

}

func (p *parser) callonUnit92() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit92()
}

func (c *current) onUnit113() (any, error) {
	return UnitBottle, nil

}

func (p *parser) callonUnit113() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit113()
}

func (c *current) onUnit118() (any, error) {
	return UnitCan, nil

}

func (p *parser) callonUnit118() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit118()
}

func (c *current) onUnit123() (any, error) {
	return UnitPacket, nil

}

func (p *parser) callonUnit123() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnit123()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
