name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

jobs:
  tests:
    strategy:
      matrix:
        go_version:
          - "1.20"

    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
        
      - name: Run tests
        run: make test

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.6.0
        with:
          test-results: test-results.json
